text_map = {
    'WELCOME_TO_GANESHA_SHOP': 'ガネーシャショップへようこそ！',
    'SALES_GATCHA': '銅のガチャは1回ジェム300個、10回連続ならジェム3000個だぞう。',
    'RECOMMEND_TEN': '10回連続まわしちゃう？',
    'RECOMMEND_GATCHA': '銅のガチャを1回まわしちゃう？',
    'RECOMMEND_GEM': 'ジェムが足りないぞう。ジェムを買うぞう？',
    'GANESHA_THANKS': 'まいど！',
    'GATCHA_SOUND_1': 'でん!',
    'GATCHA_SOUND_3': 'ででん!',
    'GATCHA_SOUND_10': 'でででん!',
    'CHRONUS_TICKET_1': 'クロノス チケット一枚',
    'CHRONUS_TICKET_3': 'クロノス チケット三枚',
    'CHRONUS_TICKET_10': 'クロノス チケット十枚',
    'BREAK_TIME_1S': '<break time="1s"/>',
    'TOTAL_TICKET_AMOUNT': 'クロノスチケットが合計{total_ticket_amount}枚手に入ったぞう。',
    'GATCHA': 'ガチャガチャを回してるよ',
    'REMAINGING_GEM': '無償ジェムは残り{remaining_free_gem}個、有償ジェムは残り{remaining_paid_gem}個です。',
    'GATCHA_AGAIN': 'もう一回{turn_times_text}まわす？',
    'END_SHOP': 'また来るんだぞう'
}
